# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Make sure this matches your primary branch name

# Allow one concurrent deployment
concurrency:
  cancel-in-progress: true
  group: pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write      # Allow the action to create a deployment
      id-token: write   # Allow the action to authenticate

    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Recommended Node version
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        
      # Step 1: Upload the built 'dist' folder as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' 
          
      # Step 2: Deploy the artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
